name: pypy
version: '7.3.13'
summary: PyPy is a fast, compliant alternative implementation of the Python language
description: |
  PyPy is a replacement for CPython. It is built using the RPython language
  that was co-developed with it. The main reason to use it instead of CPython
  is speed; it runs generally faster.
license: MIT

grade: stable
confinement: classic

apps:
  pypy:
    command: bin/pypy

base: core
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: s390x

parts:
  pypy:
    plugin: dump
    source:
      - on amd64: https://downloads.python.org/pypy/pypy2.7-v$SNAPCRAFT_PROJECT_VERSION-linux64.tar.bz2
      - on arm64: https://downloads.python.org/pypy/pypy2.7-v$SNAPCRAFT_PROJECT_VERSION-aarch64.tar.bz2
      - on s390x: https://downloads.python.org/pypy/pypy2.7-v$SNAPCRAFT_PROJECT_VERSION-s390x.tar.bz2
    override-build: |
      rm lib_pypy/_cffi_ssl/tools/make_ssl_data.py
      bin/pypy -m compileall -qx '/tests?[_/]' .
      snapcraftctl build
    stage-packages:
      - libfontconfig1
      - libxft2
      - libxrender1
